In [4]:
import sys
import os

# 1. Verifica la ruta del ejecutable de Python que está usando el Notebook
print("Python executable:", sys.executable)

# 2. Verifica si la ruta incluye tu carpeta 'venv'
if "venv" in sys.executable:
    print("✅ ¡Perfecto! El notebook está usando el entorno virtual de la carpeta 'venv'.")
else:
    print("❌ CUIDADO: El notebook está usando el Python global o de otra ruta.")

# 3. Listar paquetes instalados para confirmar
# Esto es como hacer un 'pip list' desde el notebook
import pkg_resources
installed_packages = [f"{d.project_name}=={d.version}" for d in pkg_resources.working_set]
print("\nPaquetes instalados en este entorno:")
for pkg in sorted(installed_packages):
    if "tensorflow" in pkg.lower() or "pandas" in pkg.lower():
        print(f"-> {pkg}")

Python executable: c:\Users\Juan\Desktop\MECOFIN\Redes Neuronales y Deep Learning\ufc\venv\Scripts\python.exe
✅ ¡Perfecto! El notebook está usando el entorno virtual de la carpeta 'venv'.

Paquetes instalados en este entorno:
-> pandas==3.0.1
-> tensorflow==2.21.0

In [10]:
import tensorflow as tf
import pandas as pd
import seaborn as sb
import numpy as np
import dotenv as dt

dt.load_dotenv()
pd.set_option('display.max_columns', None) # para que me muestre todas las columnas

## 1. Carga de datos y exploracion de datasets

In [12]:
# leemos el archivo de peleadores

path_peleadores = os.getenv("FIGHTERS_PATH")

df_fighters = pd.read_csv(path_peleadores)

df_fighters.head()

,Fighter_Name,Height,Weight,Reach,Stance,DOB,Wins,Losses,Draws,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Fighter_URL
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,1978-07-13,5,3,0,0.00,0%,0.00,0%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,1983-07-03,4,6,0,3.29,38%,4.41,57%,0.00,0%,77%,0.0,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman Abbasov,"5' 8""",155 lbs.,"66.0""",Orthodox,1994-02-01,28,4,0,3.00,20%,5.67,46%,0.00,0%,66%,0.0,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,"6' 2""",265 lbs.,"80.0""",Orthodox,1993-02-25,9,5,0,8.44,50%,14.06,28%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/4961467134...
4,David Abbott,"6' 0""",265 lbs.,NaN,Switch,1965-04-26,10,15,0,1.35,30%,3.55,38%,1.07,33%,66%,0.0,http://ufcstats.com/fighter-details/b361180739...

In [14]:
# leemos el archivo de peleas

path_peleas = os.getenv("FIGHTS_PATH")

df_fights = pd.read_csv(path_peleas)

df_fights.head()

,Fight_URL,Fighter_1,Fighter_2,Winner,Weight_Class,Method,End_Round,End_Time,Total_Fight_Time_Sec,Time_Format,F1_KD,F2_KD,F1_Sig_Landed,F1_Sig_Att,F2_Sig_Landed,F2_Sig_Att,F1_TD_Landed,F2_TD_Landed,F1_TD_Att,F2_TD_Att,F1_Sub_Att,F2_Sub_Att,F1_Ctrl_Sec,F2_Ctrl_Sec,F1_Head,F2_Head,F1_Body,F2_Body,F1_Leg,F2_Leg,F1_Distance,F2_Distance,F1_Clinch,F2_Clinch,F1_Ground,F2_Ground,Event_Date
0,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,Scott Morris,Open Weight Bout,Submission,1,0:20,20,No Time Limit,0,0,1,1,0,4,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1994-03-11
1,http://ufcstats.com/fight-details/4b9ae533ccb3...,Patrick Smith,Ray Wizard,Patrick Smith,Open Weight Bout,Submission,1,0:58,58,No Time Limit,0,0,1,1,1,1,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,1994-03-11
2,http://ufcstats.com/fight-details/00835554f95f...,Royce Gracie,Patrick Smith,Royce Gracie,UFC 2 Tournament Title Bout,KO/TKO,1,1:17,77,No Time Limit,0,0,4,4,1,2,1,0,2,0,0,0,0,0,3,0,0,1,1,0,0,0,1,1,3,0,1994-03-11
3,http://ufcstats.com/fight-details/aa161c715974...,Royce Gracie,Remco Pardoel,Royce Gracie,Open Weight Bout,Submission,1,1:31,91,No Time Limit,0,0,0,0,0,0,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1994-03-11
4,http://ufcstats.com/fight-details/8fbdde20b712...,Patrick Smith,Johnny Rhodes,Patrick Smith,Open Weight Bout,Submission,1,1:07,67,No Time Limit,0,0,5,12,4,9,0,0,0,0,1,0,0,0,1,2,2,0,2,2,3,4,2,0,0,0,1994-03-11